<?php

$labels = array();

// hint: this indicates the device type used to browse the website: desktop, tablet or phone
$labels['current_device'] = "Aktueller Gerätetyp";

// hint: there are three possible types of devices, desktop (or laptop) computer, tablet or phone
$labels['desktop'] = "Desktop";
$labels['tablet'] = "Tablet";
$labels['phone'] = "Telefon";
$labels['desktop_skin'] = "Desktop-Oberfläche";
$labels['tablet_skin'] = "Tablet-Oberfläche";
$labels['phone_skin'] = "Telefon-Oberfläche";
$labels['select_desktop_skin'] = "Desktop-Oberfläche wählen";
$labels['select_tablet_skin'] = "Tablet-Oberfläche wählen";
$labels['select_phone_skin'] = "Telefon-Oberfläche wählen";
$labels['disable_mobile_skin'] = "Desktop-Oberfläche verwenden";
$labels['enable_mobile_skin'] = "Mobile-Oberfläche verwenden";

