<?php

$labels = array();
$labels['current_device'] = "Current device type";
$labels['desktop'] = "Desktop";
$labels['tablet'] = "Tablet";
$labels['phone'] = "Phone";
$labels['desktop_skin'] = "Desktop skin";
$labels['tablet_skin'] = "Tablet skin";
$labels['phone_skin'] = "Phone skin";
$labels['select_desktop_skin'] = "Select desktop skin";
$labels['select_tablet_skin'] = "Select tablet skin";
$labels['select_phone_skin'] = "Select phone skin";
$labels['disable_mobile_skin'] = "Use desktop skin";
$labels['enable_mobile_skin'] = "Use mobile skin";