<?php

$labels = array();

// hint: this indicates the device type used to browse the website: desktop, tablet or phone
$labels['current_device'] = "Current device type";

// hint: there are three possible types of devices, desktop (or laptop) computer, tablet or phone
$labels['desktop'] = "Desktop";
$labels['tablet'] = "Tablet";
$labels['phone'] = "Phone";
$labels['desktop_skin'] = "Desktop skin";
$labels['tablet_skin'] = "Tablet skin";
$labels['phone_skin'] = "Phone skin";
$labels['select_desktop_skin'] = "Select desktop skin";
$labels['select_tablet_skin'] = "Select tablet skin";
$labels['select_phone_skin'] = "Select phone skin";
$labels['disable_mobile_skin'] = "Use desktop skin";
$labels['enable_mobile_skin'] = "Use mobile skin";