<?php

$labels = array();
$labels['current_device'] = "Typ urządzenia w użyciu";
$labels['desktop'] = "Desktop";
$labels['tablet'] = "Tablet";
$labels['phone'] = "Telefon";
$labels['desktop_skin'] = "Skórka na desktop";
$labels['tablet_skin'] = "Skórka na tablet";
$labels['phone_skin'] = "Skórka na telefon";
$labels['select_desktop_skin'] = "Wybierz skórkę na desktop";
$labels['select_tablet_skin'] = "Wybierz skórkę na tablet";
$labels['select_phone_skin'] = "Wybierz skórkę na telefon";
$labels['disable_mobile_skin'] = "Użyj skórki na desktop";
$labels['enable_mobile_skin'] = "Użyj skórki mobilnej";