<?php

$labels = array();
$labels['current_device'] = "Dispositivo Atual";
$labels['desktop'] = "Desktop";
$labels['tablet'] = "Tablet";
$labels['phone'] = "Smartphone";
$labels['desktop_skin'] = "Estilo Desktop";
$labels['tablet_skin'] = "Estilo Tablet";
$labels['phone_skin'] = "Estilo Smartphone";
$labels['select_desktop_skin'] = "Selecionar Desktop";
$labels['select_tablet_skin'] = "Selecionar Tablet";
$labels['select_phone_skin'] = "Selecionar Smartphone";
$labels['enable_device_autodetect'] = "Enable device autodetect";
$labels['disable_mobile_skin'] = "Use desktop skin";
$labels['enable_mobile_skin'] = "Use mobile skin";